version: "3.9"
services:
  unimock:
    build:
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:3000"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"